version: "3.1"

services:
  app:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres
    build: .
    command: yarn dev
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app